name: Deploy React Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          GENERATE_SOURCEMAP: false

      - name: Deploy to AWS Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "🚀 Starting Frontend deployment..."
           
            cd /var/www/html/react-demo
            git pull origin main
            npm ci
            npm run build
            sudo chown -R www-data:www-data /var/www/html/react-demo/build
            sudo chmod -R 755 /var/www/html/react-demo/build
            sudo systemctl reload nginx
            
            echo "✅ Frontend deployment successful!"
            echo "🌐 Visit: http://13.203.215.193"